inspect:
  path : './data/inspect'
preprocess:
  prepare:
    epoch_length : 5
    downsample : 500
    ica_method : 'fastica'
    skip_prep : False
    skip_reject : True
  overwrite : True

features:
  downsample : 500
  num_epochs : min
  prefilter :
    l_freq : 1
    h_freq : 30
  keep_channels : False
  feature_list: # You can configure different features for the same function but different args
    # The suffix will be the higher hierarchy name you put here
    PowerSpectrum:
      overwrite : False
      function : spectrum
      args:
        multitaper:
          adaptive : False
          low_bias : True
          normalization : 'full'
          verbose : 0
    RelativeBandPower1:
      overwrite : False
      function: relative_bandpower
      args :
        bands:
          delta : [1,4]
          theta : [4,8]
          alpha : [8,13]
          beta  : [13,30]
          pre_alpha : [5.5,8]
          slow_theta : [4,5.5]
        multitaper : {}
    RelativeBandPower2:
      overwrite : False
      function: relative_bandpower
      args :
        bands:
          alpha1 : [8.5, 10.5]
          alpha2 : [10.5, 12.5]
          beta1  : [12.5, 18.5]
          beta2  : [18.5, 21]
          beta3  : [21, 30]
        multitaper : {}

aggregate:
  path : './data/aggregate'
  filename : 'multidataset.csv'
  id_splitter : '/'
  features: 
    - RelativeBandPower1
    #- RelativeBandPower2

scalingAndFolding:
  MAX_FEATURES: null
  path : './data/scalingAndFolding'
  random_state : 0
  targets :
    - 'age'
  dropsToOnlyFeatures: # the targets will be appended to this in the script
    - id
    - sex
    - group
    - dataset
    - subject
    - task
  stratifiedvars :
    - dataset
    - group
    - sex
  scalings:
    scalingCombat : # name of this particular scaling config
        method : 'reCombat'
        init:
          parametric : True
          model : 'elastic_net'
          config : 
            alpha : 0.00001
          n_jobs : 7
          verbose : True
        covars :
          - dataset
          - sex
          - age
          - group
        batch : dataset # which should be the one we drop from covars for the design matrix X in combat
        rename :
          age : age_numerical
        categorical :
          - dataset
          - group
          - sex
    scalingStandard:
      method : 'StandardScaler'
  splits :
    folding:
      method : 'StratifiedKFold'
      num_folds: 5 # stratified by combination by default
    trainTestSplit:
      method : 'train_test_split'
      test_ratio : 0.3
      stratify : True # Based on combination, see script for meaning...
    all :
      method : 'all'
  visualizations:
    PCAviz:
      method : 'PCA'
      n_components : 2
      color_by : dataset
      colormap : 'viridis'

ml:
  path: './data/ml'
