inspect:
  path : './data/inspect'
preprocess:
  prepare:
    epoch_length : 5
    downsample : 500
    ica_method : 'fastica'
    skip_prep : False
    skip_reject : False
  overwrite : False

features:
  downsample : 500
  num_epochs : min
  prefilter :
    l_freq : 1
    h_freq : 30
  keep_channels : False
  feature_list: # You can configure different features for the same function but different args
    # The suffix will be the higher hierarchy name you put here
    PowerSpectrum:
      overwrite : False
      function : spectrum
      args:
        multitaper:
          adaptive : False
          low_bias : True
          normalization : 'full'
          verbose : 0
    RelativeBandPower1:
      overwrite : False
      function: relative_bandpower
      args :
        bands:
          delta : [1,4]
          theta : [4,8]
          alpha : [8,13]
          beta  : [13,30]
          pre_alpha : [5.5,8]
          slow_theta : [4,5.5]
        multitaper : {}
    RelativeBandPower2:
      overwrite : False
      function: relative_bandpower
      args :
        bands:
          alpha1 : [8.5, 10.5]
          alpha2 : [10.5, 12.5]
          beta1  : [12.5, 18.5]
          beta2  : [18.5, 21]
          beta3  : [21, 30]
        multitaper : {}

aggregate:
  path : './data/aggregate'
  filename : 'multidataset.csv'
  id_splitter : '/'
  features: 
    - RelativeBandPower1
    - RelativeBandPower2

harmonization:
  path : './data/harmonization'
  neuroCombat:
    batch : dataset
    covars :
      - dataset
      - sex
      - age
      - group
    drop :
      - id
      - subject
      - task
    categorical:
      - sex
      - group
      - dataset # Cuando entra en neurocombat el batch (Dataset) se quita de la lista
  split:
    test : 0.3
    target : 'group'
    folds : 5

classification:
  path: './data/classification'
  MAX_FEATURES: 10