[metadata]
name = eeg_raw_to_classification
url = https://github.com/alberto-jj/raw_to_classification
author = Alberto Jaramillo & Yorguin Mantilla
maintainer = Alberto Jaramillo & Yorguin Mantilla
description = Automated eeg pipeline
platforms = any
classifiers =
  Topic :: Scientific/Engineering
  Programming Language :: Python :: 3
  Intended Audience :: Science/Research
  Development Status :: 3 - Alpha
  Operating System :: POSIX :: Linux
  Operating System :: Unix
  Operating System :: MacOS
  Operating System :: Microsoft :: Windows

[options]
python_requires = >= 3.7
packages = find:
include_package_data = True

[options.entry_points]
console_scripts =
    meeg-inspect = eeg_raw_to_classification.cli.commands:inspect_main
    meeg-dataset2bids = eeg_raw_to_classification.cli.commands:dataset2bids_main
    meeg-features = eeg_raw_to_classification.cli.commands:features_main
    meeg-preprocess = eeg_raw_to_classification.cli.commands:preprocessing_main
    meeg-aggregate = eeg_raw_to_classification.cli.commands:aggregate_main